#!/usr/bin/env python3
"""Sinh app/Localization/<lang>.lproj/Localizable.strings từ bảng dịch dưới đây.

Thêm/sửa chữ: sửa bảng T rồi chạy lại. Thêm ngôn ngữ: thêm mã vào LANGS + 1 cột cho MỌI khoá
(script báo lỗi nếu thiếu). `%@` = chỗ điền chuỗi, `%d` = số — phải giữ đúng số lượng và thứ tự.
Tiếng Việt và tiếng Anh do người viết kiểm; các ngôn ngữ còn lại là bản dịch máy, cần người bản ngữ soát.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "app", "Localization")
LANGS = ["en", "vi", "zh-Hans", "ja", "ko", "es", "pt-BR", "de", "fr", "ru", "tr", "id", "th"]

T = {
"app.tagline": [
 "Play Windows (Steam) games on Mac · version %@", "Chơi game Windows (Steam) trên Mac · bản %@",
 "在 Mac 上玩 Windows（Steam）游戏 · 版本 %@", "Mac で Windows（Steam）ゲームをプレイ · バージョン %@",
 "Mac에서 Windows(Steam) 게임 플레이 · 버전 %@", "Juega a juegos de Windows (Steam) en Mac · versión %@",
 "Jogue jogos de Windows (Steam) no Mac · versão %@", "Windows-Spiele (Steam) auf dem Mac spielen · Version %@",
 "Jouez aux jeux Windows (Steam) sur Mac · version %@", "Игры для Windows (Steam) на Mac · версия %@",
 "Mac'te Windows (Steam) oyunları oynayın · sürüm %@", "Mainkan game Windows (Steam) di Mac · versi %@",
 "เล่นเกม Windows (Steam) บน Mac · เวอร์ชัน %@"],
"status.notInstalled": ["Not installed", "Chưa cài đặt", "尚未安装", "未インストール", "설치되지 않음", "Sin instalar",
 "Não instalado", "Nicht installiert", "Non installé", "Не установлено", "Kurulmadı", "Belum terpasang", "ยังไม่ได้ติดตั้ง"],
"status.running": ["Steam is running · %@", "Steam đang chạy · %@", "Steam 正在运行 · %@", "Steam 実行中 · %@",
 "Steam 실행 중 · %@", "Steam en ejecución · %@", "Steam em execução · %@", "Steam läuft · %@",
 "Steam en cours d’exécution · %@", "Steam запущен · %@", "Steam çalışıyor · %@", "Steam sedang berjalan · %@",
 "Steam กำลังทำงาน · %@"],
"status.ready": ["Ready", "Sẵn sàng", "就绪", "準備完了", "준비됨", "Listo", "Pronto", "Bereit", "Prêt", "Готово",
 "Hazır", "Siap", "พร้อม"],
"first.title": ["First-time setup", "Cài đặt lần đầu", "首次安装", "初回セットアップ", "최초 설정", "Configuración inicial",
 "Configuração inicial", "Ersteinrichtung", "Première installation", "Первоначальная установка", "İlk kurulum",
 "Penyiapan pertama", "ตั้งค่าครั้งแรก"],
"first.body": [
 "kegPlay will download Wine (~190 MB), create its own Windows “C: drive” and install Steam for Windows.\nThis takes a few minutes and needs about 3 GB of free space. Nothing is installed outside kegPlay’s data folder.",
 "kegPlay sẽ tải Wine (~190 MB), tạo một \"ổ C: Windows\" riêng và cài Steam bản Windows.\nMất vài phút, cần khoảng 3 GB trống. Không cài gì ra ngoài thư mục dữ liệu của Kegplay.",
 "kegPlay 将下载 Wine（约 190 MB），创建独立的 Windows“C 盘”，并安装 Windows 版 Steam。\n需要几分钟和约 3 GB 可用空间。不会在 kegPlay 数据文件夹之外安装任何内容。",
 "kegPlay は Wine（約 190 MB）をダウンロードし、専用の Windows「C ドライブ」を作成して Windows 版 Steam をインストールします。\n数分かかり、約 3 GB の空き容量が必要です。kegPlay のデータフォルダ以外には何もインストールしません。",
 "Kegplay가 Wine(약 190MB)을 내려받고, 전용 Windows ‘C 드라이브’를 만든 뒤 Windows용 Steam을 설치합니다.\n몇 분이 걸리며 약 3GB의 여유 공간이 필요합니다. kegPlay 데이터 폴더 밖에는 아무것도 설치하지 않습니다.",
 "kegPlay descargará Wine (~190 MB), creará su propia «unidad C:» de Windows e instalará Steam para Windows.\nTarda unos minutos y necesita unos 3 GB libres. No se instala nada fuera de la carpeta de datos de Kegplay.",
 "O kegPlay vai baixar o Wine (~190 MB), criar sua própria “unidade C:” do Windows e instalar o Steam para Windows.\nLeva alguns minutos e precisa de cerca de 3 GB livres. Nada é instalado fora da pasta de dados do Kegplay.",
 "kegPlay lädt Wine (~190 MB) herunter, legt ein eigenes Windows-„Laufwerk C:“ an und installiert Steam für Windows.\nDas dauert einige Minuten und benötigt etwa 3 GB freien Speicher. Außerhalb des Kegplay-Datenordners wird nichts installiert.",
 "kegPlay va télécharger Wine (~190 Mo), créer son propre « disque C: » Windows et installer Steam pour Windows.\nCela prend quelques minutes et nécessite environ 3 Go d’espace libre. Rien n’est installé en dehors du dossier de données de Kegplay.",
 "kegPlay загрузит Wine (~190 МБ), создаст собственный «диск C:» Windows и установит Steam для Windows.\nЭто займёт несколько минут и потребует около 3 ГБ свободного места. За пределами папки данных kegPlay ничего не устанавливается.",
 "kegPlay, Wine’ı (~190 MB) indirecek, kendi Windows “C: sürücüsünü” oluşturacak ve Windows için Steam’i kuracak.\nBirkaç dakika sürer ve yaklaşık 3 GB boş alan gerekir. kegPlay veri klasörünün dışına hiçbir şey kurulmaz.",
 "kegPlay akan mengunduh Wine (~190 MB), membuat “drive C:” Windows sendiri, dan memasang Steam untuk Windows.\nPerlu beberapa menit dan sekitar 3 GB ruang kosong. Tidak ada yang dipasang di luar folder data Kegplay.",
 "kegPlay จะดาวน์โหลด Wine (~190 MB) สร้าง “ไดรฟ์ C:” ของ Windows แยกต่างหาก และติดตั้ง Steam สำหรับ Windows\nใช้เวลาไม่กี่นาทีและต้องการพื้นที่ว่างประมาณ 3 GB จะไม่ติดตั้งสิ่งใดนอกโฟลเดอร์ข้อมูลของ kegPlay"],
"first.button": ["Start setup", "Bắt đầu cài đặt", "开始安装", "セットアップを開始", "설정 시작", "Iniciar instalación",
 "Iniciar instalação", "Einrichtung starten", "Lancer l’installation", "Начать установку", "Kurulumu başlat",
 "Mulai penyiapan", "เริ่มตั้งค่า"],
"first.data": ["Data: %@", "Dữ liệu: %@", "数据：%@", "データ：%@", "데이터: %@", "Datos: %@", "Dados: %@", "Daten: %@",
 "Données : %@", "Данные: %@", "Veri: %@", "Data: %@", "ข้อมูล: %@"],
"first.change": ["Change data folder…", "Đổi thư mục dữ liệu…", "更改数据文件夹…", "データフォルダを変更…", "데이터 폴더 변경…",
 "Cambiar carpeta de datos…", "Alterar pasta de dados…", "Datenordner ändern …", "Changer le dossier de données…",
 "Изменить папку данных…", "Veri klasörünü değiştir…", "Ubah folder data…", "เปลี่ยนโฟลเดอร์ข้อมูล…"],
"engine.dxmt": ["DXMT (recommended)", "DXMT (đề xuất)", "DXMT（推荐）", "DXMT（推奨）", "DXMT(권장)", "DXMT (recomendado)",
 "DXMT (recomendado)", "DXMT (empfohlen)", "DXMT (recommandé)", "DXMT (рекомендуется)", "DXMT (önerilen)",
 "DXMT (disarankan)", "DXMT (แนะนำ)"],
"engine.help": [
 "DXMT: DirectX 11 straight to Metal. DXVK: use it when a game misbehaves with DXMT.",
 "DXMT: DirectX 11 thẳng sang Metal. DXVK: dùng khi game lỗi với DXMT.",
 "DXMT：DirectX 11 直接转为 Metal。DXVK：游戏在 DXMT 下出问题时使用。",
 "DXMT：DirectX 11 を直接 Metal に変換。DXVK：DXMT でゲームに不具合が出るときに使用。",
 "DXMT: DirectX 11을 Metal로 직접 변환합니다. DXVK: DXMT에서 게임에 문제가 있을 때 사용하세요.",
 "DXMT: DirectX 11 directo a Metal. DXVK: úsalo si un juego falla con DXMT.",
 "DXMT: DirectX 11 direto para Metal. DXVK: use quando um jogo der problema com o DXMT.",
 "DXMT: DirectX 11 direkt nach Metal. DXVK: verwenden, wenn ein Spiel mit DXMT Probleme macht.",
 "DXMT : DirectX 11 directement vers Metal. DXVK : à utiliser si un jeu pose problème avec DXMT.",
 "DXMT: DirectX 11 напрямую в Metal. DXVK: используйте, если игра работает с DXMT некорректно.",
 "DXMT: DirectX 11’i doğrudan Metal’e çevirir. DXVK: bir oyun DXMT ile sorun çıkarırsa kullanın.",
 "DXMT: DirectX 11 langsung ke Metal. DXVK: gunakan jika game bermasalah dengan DXMT.",
 "DXMT: แปลง DirectX 11 เป็น Metal โดยตรง DXVK: ใช้เมื่อเกมมีปัญหากับ DXMT"],
"engine.help.locked": [
 "Stop Steam before switching the graphics engine.", "Tắt Steam trước khi đổi công nghệ đồ hoạ.",
 "切换图形引擎前请先关闭 Steam。", "グラフィックエンジンを切り替える前に Steam を停止してください。",
 "그래픽 엔진을 바꾸기 전에 Steam을 중지하세요.", "Detén Steam antes de cambiar el motor gráfico.",
 "Pare o Steam antes de trocar o mecanismo gráfico.", "Steam beenden, bevor die Grafik-Engine gewechselt wird.",
 "Arrêtez Steam avant de changer de moteur graphique.", "Остановите Steam перед сменой графического движка.",
 "Grafik motorunu değiştirmeden önce Steam’i durdurun.", "Hentikan Steam sebelum mengganti mesin grafis.",
 "หยุด Steam ก่อนเปลี่ยนเอนจินกราฟิก"],
"btn.openSteam": ["Open Steam", "Mở Steam", "打开 Steam", "Steam を開く", "Steam 열기", "Abrir Steam", "Abrir Steam",
 "Steam öffnen", "Ouvrir Steam", "Открыть Steam", "Steam’i aç", "Buka Steam", "เปิด Steam"],
"btn.stopSteam": ["Stop Steam", "Tắt Steam", "关闭 Steam", "Steam を停止", "Steam 중지", "Detener Steam", "Parar Steam",
 "Steam beenden", "Arrêter Steam", "Остановить Steam", "Steam’i durdur", "Hentikan Steam", "หยุด Steam"],
"help.stop": [
 "Fully stops Steam and every game running inside Kegplay.", "Tắt hẳn Steam và mọi game đang chạy trong Kegplay.",
 "完全关闭 Steam 以及 kegPlay 中运行的所有游戏。", "Steam と kegPlay 内で実行中のすべてのゲームを完全に停止します。",
 "Steam과 Kegplay에서 실행 중인 모든 게임을 완전히 종료합니다.", "Detiene por completo Steam y todos los juegos en ejecución dentro de Kegplay.",
 "Encerra totalmente o Steam e todos os jogos em execução no Kegplay.", "Beendet Steam und alle in kegPlay laufenden Spiele vollständig.",
 "Arrête complètement Steam et tous les jeux lancés dans Kegplay.", "Полностью останавливает Steam и все игры, запущенные в Kegplay.",
 "Steam’i ve kegPlay içinde çalışan tüm oyunları tamamen durdurur.", "Menghentikan Steam dan semua game yang berjalan di kegPlay sepenuhnya.",
 "หยุด Steam และทุกเกมที่ทำงานใน kegPlay โดยสมบูรณ์"],
"toggle.unblock": ["Unblock Store", "Vượt chặn Store", "解除商店封锁", "ストアのブロック回避", "스토어 차단 우회",
 "Desbloquear tienda", "Desbloquear loja", "Store entsperren", "Débloquer le magasin", "Обход блокировки магазина",
 "Mağaza engelini aş", "Buka blokir Store", "ปลดบล็อกร้านค้า"],
"help.unblock": [
 "Turn on if your ISP blocks store.steampowered.com. Applies only to Steam inside kegPlay; takes effect the next time Steam opens.",
 "Bật nếu nhà mạng chặn store.steampowered.com. Chỉ áp dụng cho Steam trong kegPlay; có hiệu lực từ lần mở Steam sau.",
 "如果运营商屏蔽了 store.steampowered.com，请开启。仅对 kegPlay 中的 Steam 生效；下次打开 Steam 时起效。",
 "プロバイダが store.steampowered.com をブロックしている場合はオンにします。kegPlay 内の Steam にのみ適用され、次回 Steam 起動時から有効になります。",
 "통신사가 store.steampowered.com을 차단하면 켜세요. kegPlay 안의 Steam에만 적용되며 다음에 Steam을 열 때부터 적용됩니다.",
 "Actívalo si tu operador bloquea store.steampowered.com. Solo afecta a Steam dentro de kegPlay; se aplica la próxima vez que abras Steam.",
 "Ative se sua operadora bloqueia store.steampowered.com. Vale apenas para o Steam dentro do kegPlay; passa a valer na próxima vez que o Steam abrir.",
 "Einschalten, wenn dein Anbieter store.steampowered.com sperrt. Gilt nur für Steam in kegPlay; wirkt ab dem nächsten Start von Steam.",
 "Activez-le si votre opérateur bloque store.steampowered.com. Ne s’applique qu’à Steam dans kegPlay ; prend effet au prochain lancement de Steam.",
 "Включите, если провайдер блокирует store.steampowered.com. Действует только для Steam внутри kegPlay; вступает в силу при следующем запуске Steam.",
 "Servis sağlayıcınız store.steampowered.com adresini engelliyorsa açın. Yalnızca kegPlay içindeki Steam için geçerlidir; Steam’in bir sonraki açılışında etkinleşir.",
 "Aktifkan jika penyedia internet memblokir store.steampowered.com. Hanya berlaku untuk Steam di dalam kegPlay; berlaku saat Steam dibuka berikutnya.",
 "เปิดใช้หากผู้ให้บริการอินเทอร์เน็ตบล็อก store.steampowered.com มีผลเฉพาะ Steam ใน kegPlay และจะเริ่มมีผลเมื่อเปิด Steam ครั้งถัดไป"],
"games.empty.title": ["No games yet", "Chưa có game nào", "还没有游戏", "ゲームはまだありません", "아직 게임이 없습니다",
 "Aún no hay juegos", "Nenhum jogo ainda", "Noch keine Spiele", "Aucun jeu pour l’instant", "Игр пока нет",
 "Henüz oyun yok", "Belum ada game", "ยังไม่มีเกม"],
"games.empty.body": [
 "Click “Open Steam”, sign in to your account and download games.\nInstalled games will appear here so you can launch them directly.",
 "Bấm \"Mở Steam\", đăng nhập tài khoản của bạn và tải game.\nGame cài xong sẽ hiện ở đây để mở thẳng.",
 "点击“打开 Steam”，登录你的账号并下载游戏。\n安装好的游戏会显示在这里，可直接启动。",
 "「Steam を開く」をクリックし、アカウントにサインインしてゲームをダウンロードしてください。\nインストール済みのゲームはここに表示され、直接起動できます。",
 "‘Steam 열기’를 눌러 계정에 로그인하고 게임을 내려받으세요.\n설치된 게임이 여기에 표시되어 바로 실행할 수 있습니다.",
 "Haz clic en «Abrir Steam», inicia sesión en tu cuenta y descarga juegos.\nLos juegos instalados aparecerán aquí para abrirlos directamente.",
 "Clique em “Abrir Steam”, entre na sua conta e baixe jogos.\nOs jogos instalados aparecem aqui para abrir diretamente.",
 "Klicke auf „Steam öffnen“, melde dich an und lade Spiele herunter.\nInstallierte Spiele erscheinen hier und lassen sich direkt starten.",
 "Cliquez sur « Ouvrir Steam », connectez-vous à votre compte et téléchargez des jeux.\nLes jeux installés apparaîtront ici pour être lancés directement.",
 "Нажмите «Открыть Steam», войдите в аккаунт и загрузите игры.\nУстановленные игры появятся здесь — их можно запускать напрямую.",
 "“Steam’i aç”a tıklayın, hesabınızda oturum açın ve oyun indirin.\nKurulan oyunlar burada görünür ve doğrudan başlatılabilir.",
 "Klik “Buka Steam”, masuk ke akun Anda, lalu unduh game.\nGame yang terpasang akan muncul di sini agar bisa langsung dijalankan.",
 "คลิก “เปิด Steam” ลงชื่อเข้าใช้บัญชีของคุณ แล้วดาวน์โหลดเกม\nเกมที่ติดตั้งแล้วจะปรากฏที่นี่เพื่อเปิดได้ทันที"],
"btn.play": ["Play", "Chơi", "开始", "プレイ", "플레이", "Jugar", "Jogar", "Spielen", "Jouer", "Играть", "Oyna", "Main", "เล่น"],
"footer.default": [
 "Offline games using DirectX 9/10/11. Games with anti-cheat or DirectX 12 only are not supported yet.",
 "Game offline DirectX 9/10/11. Game có anti-cheat hoặc chỉ DirectX 12 chưa chạy được.",
 "支持使用 DirectX 9/10/11 的单机游戏。带反作弊或仅支持 DirectX 12 的游戏暂不支持。",
 "DirectX 9/10/11 のオフラインゲームに対応。アンチチートや DirectX 12 専用のゲームは未対応です。",
 "DirectX 9/10/11 오프라인 게임을 지원합니다. 안티치트가 있거나 DirectX 12 전용인 게임은 아직 지원하지 않습니다.",
 "Juegos sin conexión con DirectX 9/10/11. Los juegos con antitrampas o solo DirectX 12 aún no son compatibles.",
 "Jogos offline com DirectX 9/10/11. Jogos com anti-cheat ou somente DirectX 12 ainda não são compatíveis.",
 "Offline-Spiele mit DirectX 9/10/11. Spiele mit Anti-Cheat oder nur DirectX 12 werden noch nicht unterstützt.",
 "Jeux hors ligne DirectX 9/10/11. Les jeux avec anti-triche ou uniquement DirectX 12 ne sont pas encore pris en charge.",
 "Офлайн-игры на DirectX 9/10/11. Игры с античитом или только с DirectX 12 пока не поддерживаются.",
 "DirectX 9/10/11 kullanan çevrimdışı oyunlar. Hile koruması olan veya yalnızca DirectX 12 destekleyen oyunlar henüz desteklenmiyor.",
 "Game offline dengan DirectX 9/10/11. Game dengan anti-cheat atau khusus DirectX 12 belum didukung.",
 "รองรับเกมออฟไลน์ที่ใช้ DirectX 9/10/11 เกมที่มีระบบป้องกันการโกงหรือใช้ DirectX 12 เท่านั้นยังไม่รองรับ"],
"link.log": ["Log", "Nhật ký", "日志", "ログ", "로그", "Registro", "Registro", "Protokoll", "Journal", "Журнал", "Günlük",
 "Log", "บันทึก"],
"link.settings": ["Settings", "Cài đặt", "设置", "設定", "설정", "Ajustes", "Ajustes", "Einstellungen", "Réglages",
 "Настройки", "Ayarlar", "Pengaturan", "การตั้งค่า"],
"alert.viewLog": ["View log", "Xem nhật ký", "查看日志", "ログを表示", "로그 보기", "Ver registro", "Ver registro",
 "Protokoll anzeigen", "Voir le journal", "Открыть журнал", "Günlüğü göster", "Lihat log", "ดูบันทึก"],
"btn.close": ["Close", "Đóng", "关闭", "閉じる", "닫기", "Cerrar", "Fechar", "Schließen", "Fermer", "Закрыть", "Kapat",
 "Tutup", "ปิด"],
"btn.done": ["Done", "Xong", "完成", "完了", "완료", "Listo", "Concluído", "Fertig", "Terminé", "Готово", "Bitti", "Selesai",
 "เสร็จสิ้น"],
"log.openFolder": ["Open log folder", "Mở thư mục log", "打开日志文件夹", "ログフォルダを開く", "로그 폴더 열기",
 "Abrir carpeta de registros", "Abrir pasta de registros", "Protokollordner öffnen", "Ouvrir le dossier des journaux",
 "Открыть папку журналов", "Günlük klasörünü aç", "Buka folder log", "เปิดโฟลเดอร์บันทึก"],
"settings.data.title": ["Data folder", "Thư mục dữ liệu", "数据文件夹", "データフォルダ", "데이터 폴더", "Carpeta de datos",
 "Pasta de dados", "Datenordner", "Dossier de données", "Папка данных", "Veri klasörü", "Folder data", "โฟลเดอร์ข้อมูล"],
"settings.data.desc": [
 "Holds Wine, Steam for Windows and downloaded games. Deleting this folder removes kegPlay completely.",
 "Nơi chứa Wine, Steam bản Windows và game đã tải. Xoá thư mục này là gỡ sạch Kegplay.",
 "存放 Wine、Windows 版 Steam 和已下载的游戏。删除此文件夹即可彻底卸载 kegPlay。",
 "Wine、Windows 版 Steam、ダウンロードしたゲームを保存します。このフォルダを削除すると kegPlay は完全に削除されます。",
 "Wine, Windows용 Steam, 내려받은 게임이 저장됩니다. 이 폴더를 삭제하면 Kegplay가 완전히 제거됩니다.",
 "Contiene Wine, Steam para Windows y los juegos descargados. Al eliminar esta carpeta se elimina kegPlay por completo.",
 "Guarda o Wine, o Steam para Windows e os jogos baixados. Apagar esta pasta remove o kegPlay por completo.",
 "Enthält Wine, Steam für Windows und heruntergeladene Spiele. Wird dieser Ordner gelöscht, ist kegPlay vollständig entfernt.",
 "Contient Wine, Steam pour Windows et les jeux téléchargés. Supprimer ce dossier désinstalle complètement Kegplay.",
 "Здесь хранятся Wine, Steam для Windows и загруженные игры. Удаление этой папки полностью удаляет Kegplay.",
 "Wine, Windows için Steam ve indirilen oyunlar burada tutulur. Bu klasörü silmek kegPlay’i tamamen kaldırır.",
 "Berisi Wine, Steam untuk Windows, dan game yang diunduh. Menghapus folder ini menghapus kegPlay sepenuhnya.",
 "เก็บ Wine, Steam สำหรับ Windows และเกมที่ดาวน์โหลด การลบโฟลเดอร์นี้จะลบ kegPlay ออกทั้งหมด"],
"settings.reveal": ["Show in Finder", "Mở trong Finder", "在访达中显示", "Finder に表示", "Finder에서 보기", "Mostrar en Finder",
 "Mostrar no Finder", "Im Finder zeigen", "Afficher dans le Finder", "Показать в Finder", "Finder’da göster",
 "Tampilkan di Finder", "แสดงใน Finder"],
"settings.change": ["Change…", "Đổi…", "更改…", "変更…", "변경…", "Cambiar…", "Alterar…", "Ändern …", "Modifier…", "Изменить…",
 "Değiştir…", "Ubah…", "เปลี่ยน…"],
"settings.default": ["Use default", "Về mặc định", "恢复默认", "デフォルトに戻す", "기본값 사용", "Usar predeterminada",
 "Usar padrão", "Standard verwenden", "Par défaut", "По умолчанию", "Varsayılanı kullan", "Gunakan bawaan", "ใช้ค่าเริ่มต้น"],
"settings.reuse": [
 "Already have a kegPlay script folder (with bottles/ and runtime/)? Choose it here to reuse its Steam and downloaded games.",
 "Đã có sẵn thư mục kegPlay bản script (có bottles/, runtime/)? Chọn nó ở đây để dùng lại Steam và game đã tải.",
 "已有脚本版 kegPlay 文件夹（含 bottles/ 和 runtime/）？在此选择它即可继续使用其中的 Steam 和已下载的游戏。",
 "スクリプト版 kegPlay のフォルダ（bottles/ と runtime/ を含む）をお持ちですか？ここで選ぶと、その Steam とダウンロード済みゲームを再利用できます。",
 "스크립트판 kegPlay 폴더(bottles/, runtime/ 포함)가 이미 있나요? 여기서 선택하면 그 Steam과 내려받은 게임을 그대로 쓸 수 있습니다.",
 "¿Ya tienes una carpeta de kegPlay en versión script (con bottles/ y runtime/)? Elígela aquí para reutilizar su Steam y los juegos descargados.",
 "Já tem uma pasta do kegPlay em versão script (com bottles/ e runtime/)? Escolha-a aqui para reutilizar o Steam e os jogos baixados.",
 "Schon einen Kegplay-Skriptordner (mit bottles/ und runtime/)? Hier auswählen, um dessen Steam und heruntergeladene Spiele weiterzuverwenden.",
 "Vous avez déjà un dossier kegPlay en version script (avec bottles/ et runtime/) ? Choisissez-le ici pour réutiliser son Steam et les jeux téléchargés.",
 "Уже есть папка скриптовой версии kegPlay (с bottles/ и runtime/)? Выберите её здесь, чтобы использовать её Steam и загруженные игры.",
 "Zaten betik sürümü bir kegPlay klasörünüz (bottles/ ve runtime/ içeren) var mı? Steam’ini ve indirilen oyunlarını yeniden kullanmak için burada seçin.",
 "Sudah punya folder kegPlay versi skrip (berisi bottles/ dan runtime/)? Pilih di sini untuk memakai kembali Steam dan game yang sudah diunduh.",
 "มีโฟลเดอร์ kegPlay แบบสคริปต์อยู่แล้ว (มี bottles/ และ runtime/) ใช่ไหม เลือกที่นี่เพื่อใช้ Steam และเกมที่ดาวน์โหลดไว้ต่อได้"],
"settings.about": [
 "Built on Wine, DXMT, DXVK, MoltenVK and SpoofDPI. Not affiliated with Valve, Apple or Microsoft.",
 "Dựng trên Wine, DXMT, DXVK, MoltenVK, SpoofDPI. Không liên kết với Valve, Apple hay Microsoft.",
 "基于 Wine、DXMT、DXVK、MoltenVK 和 SpoofDPI 构建。与 Valve、Apple 或 Microsoft 无关联。",
 "Wine、DXMT、DXVK、MoltenVK、SpoofDPI を利用しています。Valve、Apple、Microsoft とは無関係です。",
 "Wine, DXMT, DXVK, MoltenVK, SpoofDPI를 기반으로 합니다. Valve, Apple, Microsoft와 관련이 없습니다.",
 "Basado en Wine, DXMT, DXVK, MoltenVK y SpoofDPI. Sin relación con Valve, Apple ni Microsoft.",
 "Baseado em Wine, DXMT, DXVK, MoltenVK e SpoofDPI. Sem vínculo com Valve, Apple ou Microsoft.",
 "Basiert auf Wine, DXMT, DXVK, MoltenVK und SpoofDPI. Keine Verbindung zu Valve, Apple oder Microsoft.",
 "Repose sur Wine, DXMT, DXVK, MoltenVK et SpoofDPI. Sans lien avec Valve, Apple ou Microsoft.",
 "Основано на Wine, DXMT, DXVK, MoltenVK и SpoofDPI. Не связано с Valve, Apple или Microsoft.",
 "Wine, DXMT, DXVK, MoltenVK ve SpoofDPI üzerine kuruludur. Valve, Apple veya Microsoft ile bağlantılı değildir.",
 "Dibangun di atas Wine, DXMT, DXVK, MoltenVK, dan SpoofDPI. Tidak berafiliasi dengan Valve, Apple, atau Microsoft.",
 "สร้างบน Wine, DXMT, DXVK, MoltenVK และ SpoofDPI ไม่มีส่วนเกี่ยวข้องกับ Valve, Apple หรือ Microsoft"],
"panel.prompt": ["Choose", "Chọn", "选择", "選択", "선택", "Elegir", "Escolher", "Auswählen", "Choisir", "Выбрать", "Seç",
 "Pilih", "เลือก"],
"panel.message": ["Choose kegPlay’s data folder", "Chọn thư mục dữ liệu của kegPlay", "选择 kegPlay 的数据文件夹",
 "kegPlay のデータフォルダを選択", "kegPlay 데이터 폴더 선택", "Elige la carpeta de datos de kegPlay",
 "Escolha a pasta de dados do kegPlay", "Kegplay-Datenordner auswählen", "Choisissez le dossier de données de kegPlay",
 "Выберите папку данных kegPlay", "kegPlay veri klasörünü seçin", "Pilih folder data kegPlay", "เลือกโฟลเดอร์ข้อมูลของ kegPlay"],
"busy.openSteam": ["Opening Steam (%@)", "Mở Steam (%@)", "正在打开 Steam（%@）", "Steam を起動中（%@）", "Steam 여는 중(%@)",
 "Abriendo Steam (%@)", "Abrindo o Steam (%@)", "Steam wird geöffnet (%@)", "Ouverture de Steam (%@)", "Запуск Steam (%@)",
 "Steam açılıyor (%@)", "Membuka Steam (%@)", "กำลังเปิด Steam (%@)"],
"busy.play": ["Launching %@", "Mở %@", "正在启动 %@", "%@ を起動中", "%@ 실행 중", "Iniciando %@", "Iniciando %@",
 "%@ wird gestartet", "Lancement de %@", "Запуск %@", "%@ başlatılıyor", "Menjalankan %@", "กำลังเปิด %@"],
"busy.stop": ["Stopping Steam", "Tắt Steam", "正在关闭 Steam", "Steam を停止中", "Steam 중지 중", "Deteniendo Steam",
 "Parando o Steam", "Steam wird beendet", "Arrêt de Steam", "Остановка Steam", "Steam durduruluyor", "Menghentikan Steam",
 "กำลังหยุด Steam"],
"busy.unblockOn": ["Turning on Store unblock", "Bật vượt chặn Store", "正在开启商店解锁", "ストアのブロック回避をオンにしています",
 "스토어 차단 우회 켜는 중", "Activando desbloqueo de la tienda", "Ativando desbloqueio da loja", "Store-Entsperrung wird aktiviert",
 "Activation du déblocage du magasin", "Включение обхода блокировки", "Mağaza engeli aşma açılıyor", "Mengaktifkan buka blokir Store",
 "กำลังเปิดการปลดบล็อกร้านค้า"],
"busy.unblockOff": ["Turning off Store unblock", "Tắt vượt chặn Store", "正在关闭商店解锁", "ストアのブロック回避をオフにしています",
 "스토어 차단 우회 끄는 중", "Desactivando desbloqueo de la tienda", "Desativando desbloqueio da loja", "Store-Entsperrung wird deaktiviert",
 "Désactivation du déblocage du magasin", "Отключение обхода блокировки", "Mağaza engeli aşma kapatılıyor", "Menonaktifkan buka blokir Store",
 "กำลังปิดการปลดบล็อกร้านค้า"],
"busy.downloading": ["Downloading… %@", "Đang tải… %@", "正在下载… %@", "ダウンロード中… %@", "내려받는 중… %@", "Descargando… %@",
 "Baixando… %@", "Wird geladen … %@", "Téléchargement… %@", "Загрузка… %@", "İndiriliyor… %@", "Mengunduh… %@", "กำลังดาวน์โหลด… %@"],
"busy.working": ["Working… this can take a few minutes.", "Đang xử lý… có thể mất vài phút.", "处理中…可能需要几分钟。",
 "処理中… 数分かかることがあります。", "처리 중… 몇 분 걸릴 수 있습니다.", "Trabajando… puede tardar unos minutos.",
 "Processando… pode levar alguns minutos.", "Wird bearbeitet … das kann einige Minuten dauern.",
 "Traitement en cours… cela peut prendre quelques minutes.", "Выполняется… это может занять несколько минут.",
 "İşleniyor… birkaç dakika sürebilir.", "Sedang memproses… mungkin perlu beberapa menit.", "กำลังดำเนินการ… อาจใช้เวลาสักครู่"],
"alert.failed": [
 "“%@” did not finish (step %@, code %@). Open the log for details.",
 "\"%@\" chưa xong (bước %@, mã %@). Mở nhật ký để xem chi tiết.",
 "“%@”未完成（步骤 %@，代码 %@）。请打开日志查看详情。",
 "「%@」は完了しませんでした（ステップ %@、コード %@）。詳細はログを確認してください。",
 "‘%@’ 작업이 완료되지 않았습니다(단계 %@, 코드 %@). 자세한 내용은 로그를 확인하세요.",
 "«%@» no terminó (paso %@, código %@). Abre el registro para ver los detalles.",
 "“%@” não foi concluído (etapa %@, código %@). Abra o registro para ver os detalhes.",
 "„%@“ wurde nicht abgeschlossen (Schritt %@, Code %@). Details stehen im Protokoll.",
 "« %@ » n’a pas abouti (étape %@, code %@). Ouvrez le journal pour plus de détails.",
 "«%@» не завершено (шаг %@, код %@). Подробности — в журнале.",
 "“%@” tamamlanamadı (adım %@, kod %@). Ayrıntılar için günlüğü açın.",
 "“%@” belum selesai (langkah %@, kode %@). Buka log untuk detailnya.",
 "“%@” ทำไม่สำเร็จ (ขั้นตอน %@ รหัส %@) เปิดบันทึกเพื่อดูรายละเอียด"],
"settings.language": ["Language", "Ngôn ngữ", "语言", "言語", "언어", "Idioma", "Idioma", "Sprache", "Langue", "Язык", "Dil",
 "Bahasa", "ภาษา"],
"settings.language.system": ["Same as macOS", "Theo macOS", "跟随 macOS", "macOS に合わせる", "macOS와 동일", "Igual que macOS",
 "Igual ao macOS", "Wie macOS", "Comme macOS", "Как в macOS", "macOS ile aynı", "Sama seperti macOS", "ตาม macOS"],
"err.cannotRun": ["ERROR: could not run %@: %@", "LỖI: không chạy được %@: %@", "错误：无法运行 %@：%@", "エラー：%@ を実行できません：%@",
 "오류: %@ 실행 불가: %@", "ERROR: no se pudo ejecutar %@: %@", "ERRO: não foi possível executar %@: %@",
 "FEHLER: %@ konnte nicht ausgeführt werden: %@", "ERREUR : impossible d’exécuter %@ : %@", "ОШИБКА: не удалось запустить %@: %@",
 "HATA: %@ çalıştırılamadı: %@", "GALAT: tidak dapat menjalankan %@: %@", "ข้อผิดพลาด: ไม่สามารถเรียกใช้ %@: %@"],
"settings.asciiInput": ["Switch keyboard to ABC while in a game", "Tự chuyển bộ gõ sang ABC khi vào game", "进入游戏时自动切换到 ABC 键盘",
 "ゲーム中はキーボードを ABC に自動で切り替える", "게임 중에는 키보드를 ABC로 자동 전환", "Cambiar el teclado a ABC al entrar en un juego",
 "Mudar o teclado para ABC ao entrar em um jogo", "Tastatur im Spiel automatisch auf ABC umschalten", "Passer le clavier en ABC pendant le jeu",
 "Переключать клавиатуру на ABC в игре", "Oyundayken klavyeyi ABC’ye geçir", "Ganti papan ketik ke ABC saat masuk game",
 "สลับแป้นพิมพ์เป็น ABC เมื่อเข้าเกม"],
"settings.asciiInput.desc": [
 "Input methods (Vietnamese Telex, Chinese, Japanese, Korean…) hold keys back to compose text, so W/A/S/D show up in a white box and movement stutters. Your input method is restored when you leave the game window. kegPlay must stay open.",
 "Bộ gõ (Telex, VNI, tiếng Trung, Nhật, Hàn…) giữ phím lại để ghép chữ, nên W/A/S/D hiện thành ô chữ trắng và di chuyển bị khựng. Bộ gõ cũ được trả lại khi bạn rời cửa sổ game. Cần để kegPlay mở.",
 "输入法（越南语 Telex、中文、日文、韩文等）会暂存按键以组字，导致 W/A/S/D 显示在白色框中、移动卡顿。离开游戏窗口时会恢复原输入法。需保持 kegPlay 打开。",
 "入力メソッド（ベトナム語 Telex、中国語、日本語、韓国語など）は文字変換のためにキーを保持するため、W/A/S/D が白い枠に表示され、移動が引っかかります。ゲームウインドウを離れると元の入力メソッドに戻ります。kegPlay を開いたままにしてください。",
 "입력기(베트남어 Telex, 중국어, 일본어, 한국어 등)는 글자를 조합하려고 키를 잡아 두기 때문에 W/A/S/D가 흰 상자에 표시되고 이동이 끊깁니다. 게임 창을 벗어나면 원래 입력기로 돌아갑니다. Kegplay를 열어 두어야 합니다.",
 "Los métodos de entrada (Telex vietnamita, chino, japonés, coreano…) retienen las teclas para componer texto, así que W/A/S/D aparecen en un cuadro blanco y el movimiento se entrecorta. Tu método de entrada se restaura al salir de la ventana del juego. kegPlay debe seguir abierto.",
 "Os métodos de entrada (Telex vietnamita, chinês, japonês, coreano…) seguram as teclas para compor texto, então W/A/S/D aparecem em uma caixa branca e o movimento trava. Seu método de entrada é restaurado ao sair da janela do jogo. O kegPlay precisa ficar aberto.",
 "Eingabemethoden (vietnamesisches Telex, Chinesisch, Japanisch, Koreanisch …) halten Tasten zum Zusammensetzen von Text zurück, sodass W/A/S/D in einem weißen Feld erscheinen und die Bewegung stockt. Beim Verlassen des Spielfensters wird deine Eingabemethode wiederhergestellt. kegPlay muss geöffnet bleiben.",
 "Les méthodes de saisie (Telex vietnamien, chinois, japonais, coréen…) retiennent les touches pour composer le texte : W/A/S/D s’affichent dans un cadre blanc et les déplacements saccadent. Votre méthode de saisie est rétablie quand vous quittez la fenêtre du jeu. kegPlay doit rester ouvert.",
 "Методы ввода (вьетнамский Telex, китайский, японский, корейский…) удерживают клавиши для набора текста, поэтому W/A/S/D появляются в белом окошке, а движение прерывается. При выходе из окна игры ваш метод ввода возвращается. kegPlay должен оставаться открытым.",
 "Giriş yöntemleri (Vietnamca Telex, Çince, Japonca, Korece…) metin oluşturmak için tuşları bekletir; bu yüzden W/A/S/D beyaz bir kutuda görünür ve hareket takılır. Oyun penceresinden çıkınca giriş yönteminiz geri yüklenir. kegPlay açık kalmalıdır.",
 "Metode input (Telex Vietnam, Mandarin, Jepang, Korea…) menahan tombol untuk menyusun teks, sehingga W/A/S/D muncul di kotak putih dan gerakan tersendat. Metode input Anda dikembalikan saat keluar dari jendela game. kegPlay harus tetap terbuka.",
 "วิธีป้อนข้อมูล (Telex เวียดนาม จีน ญี่ปุ่น เกาหลี…) จะพักปุ่มไว้เพื่อประกอบข้อความ ทำให้ W/A/S/D ไปแสดงในกล่องสีขาวและการเคลื่อนที่สะดุด วิธีป้อนข้อมูลเดิมจะกลับมาเมื่อออกจากหน้าต่างเกม ต้องเปิด kegPlay ค้างไว้"],
"game.downloading": ["Downloading in Steam…", "Đang tải trong Steam…", "正在 Steam 中下载…", "Steam でダウンロード中…", "Steam에서 내려받는 중…",
 "Descargando en Steam…", "Baixando no Steam…", "Wird in Steam geladen …", "Téléchargement dans Steam…", "Загружается в Steam…",
 "Steam’de indiriliyor…", "Sedang diunduh di Steam…", "กำลังดาวน์โหลดใน Steam…"],
"update.available": ["kegPlay %@ is available.", "Đã có kegPlay %@.", "kegPlay %@ 已发布。", "kegPlay %@ が利用可能です。", "kegPlay %@ 버전이 나왔습니다.",
 "kegPlay %@ ya está disponible.", "O kegPlay %@ está disponível.", "kegPlay %@ ist verfügbar.", "kegPlay %@ est disponible.",
 "Доступна версия kegPlay %@.", "kegPlay %@ yayımlandı.", "kegPlay %@ sudah tersedia.", "kegPlay %@ พร้อมให้ใช้งานแล้ว"],
"update.get": ["Download", "Tải về", "下载", "ダウンロード", "내려받기", "Descargar", "Baixar", "Herunterladen", "Télécharger", "Скачать",
 "İndir", "Unduh", "ดาวน์โหลด"],
"link.help": ["Troubleshooting", "Gỡ lỗi", "故障排除", "トラブルシューティング", "문제 해결", "Solución de problemas", "Solução de problemas",
 "Fehlerbehebung", "Dépannage", "Устранение неполадок", "Sorun giderme", "Pemecahan masalah", "แก้ปัญหา"],
"alert.help": ["How to fix", "Cách xử lý", "解决方法", "対処方法", "해결 방법", "Cómo solucionarlo", "Como resolver", "Lösung anzeigen",
 "Comment résoudre", "Как исправить", "Nasıl düzeltilir", "Cara memperbaiki", "วิธีแก้ไข"],
}


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main() -> int:
    bad = 0
    for key, vals in T.items():
        if len(vals) != len(LANGS):
            print(f"LỖI: {key} có {len(vals)} bản dịch, cần {len(LANGS)}"); bad += 1; continue
        want = re.findall(r"%[@d]", vals[0])
        for lang, v in zip(LANGS, vals):
            if re.findall(r"%[@d]", v) != want:
                print(f"LỖI: {key} [{lang}] lệch chỗ điền: {v!r}"); bad += 1
    if bad:
        return 1
    for i, lang in enumerate(LANGS):
        d = os.path.join(OUT, f"{lang}.lproj")
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "Localizable.strings"), "w", encoding="utf-8") as f:
            f.write("/* Sinh tự động bởi tools/make-localizations.py — sửa ở đó, đừng sửa file này. */\n")
            for key, vals in T.items():
                f.write(f'"{key}" = "{esc(vals[i])}";\n')
    print(f"==> {len(LANGS)} ngôn ngữ × {len(T)} chuỗi → {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
